INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tatarstan', 'Альметьевск', 'Россия', '2024-05-31 20:00:00', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_anapa', 'Анапа', 'Россия', '2024-05-31 20:00:01', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_barnaul', 'Барнаул', 'Россия', '2024-05-31 20:00:02', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_bahchisarai', 'Бахчисарай', 'Россия', '2024-05-31 20:00:03', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_belgorod', 'Белгород', 'Россия', '2024-05-31 20:00:04', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_biysk', 'Бийск', 'Россия', '2024-05-31 20:00:05', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_bryansk', 'Брянск', 'Россия', '2024-05-31 20:00:06', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_Velikiy_Novgorod', 'Великий Новгород ', 'Россия', '2024-05-31 20:00:07', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@umvl24', 'Владивосток', 'Россия', '2024-05-31 20:00:08', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_volgograd', 'Волгоград', 'Россия', '2024-05-31 20:00:09', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_vrn', 'Воронеж', 'Россия', '2024-05-31 20:00:10', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_ekaterinburg', 'Екатеринбург', 'Россия', '2024-05-31 20:00:11', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_izhevsk', 'Ижевск', 'Россия', '2024-05-31 20:00:12', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_irkutsk', 'Иркутск', 'Россия', '2024-05-31 20:00:13', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_kazan', 'Казань', 'Россия', '2024-05-31 20:00:14', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_kaliningrad', 'Калининград', 'Россия', '2024-05-31 20:00:14', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_kirov', 'Киров', 'Россия', '2024-05-31 20:00:15', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_KMV', 'Кисловодск/Пятигорск', 'Россия', '2024-05-31 20:00:16', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_kolomna', 'Коломна', 'Россия', '2024-05-31 20:00:17', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_krasnodar', 'Краснодар', 'Россия', '2024-05-31 20:00:18', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_kursk', 'Курск', 'Россия', '2024-05-31 20:00:19', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_leninskkuznetskiy', 'Ленинск- Кузнецкий ', 'Россия', '2024-05-31 20:00:20', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_magnitogorsk', 'Магнитогорск', 'Россия', '2024-05-31 20:00:21', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_maikop', 'Майкоп', 'Россия', '2024-05-31 20:00:22', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_moscow', 'Москва ', 'Россия', '2024-05-31 20:00:23', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_murmansk', 'Мурманск ', 'Россия', '2024-05-31 20:00:24', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_chelny', 'Набережные Челны', 'Россия', '2024-05-31 20:00:25', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_nevinnomyssk', 'Невинномысск', 'Россия', '2024-05-31 20:00:26', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_Nizhniy_Novgorod', 'Нижний Новгород', 'Россия', '2024-05-31 20:00:27', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_nvkz', 'Новокузнецк', 'Россия', '2024-05-31 20:00:28', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_novosibirsk', 'Новосибирск', 'Россия', '2024-05-31 20:00:29', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditaciiomsk', 'Омск', 'Россия', '2024-05-31 20:00:30', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_orel', 'Орел', 'Россия', '2024-05-31 20:00:31', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_orenburg', 'Оренбург', 'Россия', '2024-05-31 20:00:32', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_perm', 'Пермь', 'Россия', '2024-05-31 20:00:33', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_petrozavodsk', 'Петрозаводск', 'Россия', '2024-05-31 20:00:34', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_pskov', 'Псков', 'Россия', '2024-05-31 20:00:35', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_rnd', 'Ростов-на-Дону ', 'Россия', '2024-05-31 20:00:36', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_samara', 'Самара', 'Россия', '2024-05-31 20:00:37', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_piter', 'Санкт-Петербург', 'Россия', '2024-05-31 20:00:38', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_saratov', 'Саратов', 'Россия', '2024-05-31 20:00:39', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_sevastopol', 'Севастополь', 'Россия', '2024-05-31 20:00:40', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_simferopol', 'Симферополь', 'Россия', '2024-05-31 20:00:40', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_sochi', 'Сочи', 'Россия', '2024-05-31 20:00:41', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_sterlitamak', 'Стерлитамак', 'Россия', '2024-05-31 20:00:42', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tver', 'Тверь', 'Россия', '2024-05-31 20:00:43', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_TLT', 'Тольятти', 'Россия', '2024-05-31 20:00:44', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tula', 'Тула ', 'Россия', '2024-05-31 20:00:45', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tomsk', 'Томск', 'Россия', '2024-05-31 20:00:46', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tumen', 'Тюмень', 'Россия', '2024-05-31 20:00:47', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_ulyanovsk', 'Ульяновск', 'Россия', '2024-05-31 20:00:48', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_ufa', 'Уфа', 'Россия', '2024-05-31 20:00:49', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_khabarovsk', 'Хабаровск', 'Россия', '2024-05-31 20:00:50', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_chelyabinsk', 'Челябинск ', 'Россия', '2024-05-31 20:00:51', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_yalta', 'Ялта', 'Россия', '2024-05-31 20:00:52', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_yaroslavl', 'Ярославль', 'Россия', '2024-05-31 20:00:53', 'f_zoidberg');

INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_baku', 'Баку', 'МИР', '2024-05-31 20:00:54', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_bishkek', 'Бишкек', 'МИР', '2024-05-31 20:00:55', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_goa', 'Гоа', 'МИР', '2024-05-31 20:00:56', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_danang', 'Дананг', 'МИР', '2024-05-31 20:00:57', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_minsk', 'Минск', 'МИР', '2024-05-31 20:00:58', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_borisov', 'Борисов', 'МИР', '2024-05-31 20:00:59', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_muine', 'МуйНе', 'МИР', '2024-05-31 20:01:00', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_riga', 'Рига', 'МИР', '2024-05-31 20:01:01', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tbilisi', 'Тбилиси', 'МИР', '2024-05-31 20:01:02', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_tashkent', 'Ташкент', 'МИР', '2024-05-31 20:01:03', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_bali', 'Убуд (Бали)', 'МИР', '2024-05-31 20:01:04', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_almaty', 'Алматы', 'МИР', '2024-05-31 20:01:05', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_bulgaria', 'Болгария', 'МИР', '2024-05-31 20:01:06', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_lithuania', 'Литва', 'МИР', '2024-05-31 20:01:07', 'f_zoidberg');

INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_arkhangelsk', 'Архангельск', 'На паузе', '2024-05-31 20:01:08', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_kemerovo', 'Кемерово', 'На паузе', '2024-05-31 20:01:09', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_Alania', 'Аланья', 'На паузе', '2024-05-31 20:01:10', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_yalta', 'Ялта', 'На паузе', '2024-05-31 20:01:11', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@umvl24', 'Владивосток', 'На паузе', '2024-05-31 20:01:12', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_stavropol', 'Ставрополь', 'На паузе', '2024-05-31 20:01:12', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_penza', 'Пенза', 'На паузе', '2024-05-31 20:01:13', 'f_zoidberg');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY, GROUP_ADDED_AT, GROUP_ADDED_BY)
VALUES ('@urokimeditacii_norilsk', 'Норильск', 'На паузе', '2024-05-31 20:01:14', 'f_zoidberg');


