INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tatarstan', 'Альметьевск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_anapa', 'Анапа' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_barnaul', 'Барнаул' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_bahchisarai', 'Бахчисарай' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_belgorod', 'Белгород' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_biysk', 'Бийск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_bryansk', 'Брянск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_Velikiy_Novgorod', 'Великий Новгород ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@umvl24', 'Владивосток' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_volgograd', 'Волгоград' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_vrn', 'Воронеж' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_ekaterinburg', 'Екатеринбург' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_izhevsk', 'Ижевск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_irkutsk', 'Иркутск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_kazan', 'Казань' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_kaliningrad', 'Калининград' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_kirov', 'Киров' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_KMV', 'Кисловодск/Пятигорск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_kolomna', 'Коломна' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_krasnodar', 'Краснодар' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_kursk', 'Курск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_leninskkuznetskiy', 'Ленинск- Кузнецкий ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_magnitogorsk', 'Магнитогорск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_maikop', 'Майкоп' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_moscow', 'Москва ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_murmansk', 'Мурманск ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_chelny', 'Набережные Челны' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_nevinnomyssk', 'Невинномысск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_Nizhniy_Novgorod', 'Нижний Новгород' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_nvkz', 'Новокузнецк' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_novosibirsk', 'Новосибирск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditaciiomsk', 'Омск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_orel', 'Орел' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_orenburg', 'Оренбург' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_perm', 'Пермь' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_petrozavodsk', 'Петрозаводск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_pskov', 'Псков' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_rnd', 'Ростов-на-Дону ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_samara', 'Самара' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_piter', 'Санкт-Петербург' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_saratov', 'Саратов' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_sevastopol', 'Севастополь' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_simferopol', 'Симферополь' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_sochi', 'Сочи' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_sterlitamak', 'Стерлитамак' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tver', 'Тверь' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_TLT', 'Тольятти' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tula', 'Тула ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tomsk', 'Томск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tumen', 'Тюмень' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_ulyanovsk', 'Ульяновск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_ufa', 'Уфа' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_khabarovsk', 'Хабаровск' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_chelyabinsk', 'Челябинск ' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_yalta', 'Ялта' , 'Россия');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_yaroslavl', 'Ярославль' , 'Россия');

INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_baku', 'Баку' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_bishkek', 'Бишкек' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_goa', 'Гоа' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_danang', 'Дананг' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_minsk', 'Минск' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_borisov', 'Борисов' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_muine', 'МуйНе' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_riga', 'Рига' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tbilisi', 'Тбилиси' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_tashkent', 'Ташкент' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_bali', 'Убуд (Бали)' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_almaty', 'Алматы' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_bulgaria', 'Болгария' , 'МИР');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_lithuania', 'Литва' , 'МИР');

INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_arkhangelsk', 'Архангельск' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_kemerovo', 'Кемерово' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_Alania', 'Аланья' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_yalta', 'Ялта' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@umvl24', 'Владивосток' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_stavropol', 'Ставрополь' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_penza', 'Пенза' , 'На паузе');
INSERT INTO GROUPS(GROUP_INTERNAL_NAME, GROUP_CITY, GROUP_CATEGORY) VALUES ('@urokimeditacii_norilsk', 'Норильск' , 'На паузе');


