INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (1, '2024-05-31', 21);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (2, '2024-05-31', 78);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (3, '2024-05-31', 88);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (4, '2024-05-31', 27);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (5, '2024-05-31', 36);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (6, '2024-05-31', 68);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (7, '2024-05-31', 51);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (8, '2024-05-31', 17);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (9, '2024-05-31', 0);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (10, '2024-05-31', 65);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (11, '2024-05-31', 94);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (12, '2024-05-31', 253);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (13, '2024-05-31', 93);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (14, '2024-05-31', 106);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (15, '2024-05-31', 209);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (16, '2024-05-31', 128);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (17, '2024-05-31', 33);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (18, '2024-05-31', 57);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (19, '2024-05-31', 28);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (20, '2024-05-31', 336);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (21, '2024-05-31', 40);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (22, '2024-05-31', 23);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (23, '2024-05-31', 47);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (24, '2024-05-31', 29);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (25, '2024-05-31', 1451);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (26, '2024-05-31', 76);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (27, '2024-05-31', 26);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (28, '2024-05-31', 17);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (29, '2024-05-31', 101);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (30, '2024-05-31', 18);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (31, '2024-05-31', 272);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (32, '2024-05-31', 192);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (33, '2024-05-31', 35);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (34, '2024-05-31', 56);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (35, '2024-05-31', 131);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (36, '2024-05-31', 38);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (37, '2024-05-31', 29);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (38, '2024-05-31', 327);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (39, '2024-05-31', 66);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (40, '2024-05-31', 778);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (41, '2024-05-31', 77);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (42, '2024-05-31', 43);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (43, '2024-05-31', 82);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (44, '2024-05-31', 186);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (45, '2024-05-31', 19);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (46, '2024-05-31', 45);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (47, '2024-05-31', 27);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (48, '2024-05-31', 0);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (49, '2024-05-31', 81);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (50, '2024-05-31', 164);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (51, '2024-05-31', 49);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (52, '2024-05-31', 140);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (53, '2024-05-31', 197);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (54, '2024-05-31', 83);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (55, '2024-05-31', 52);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (56, '2024-05-31', 64);

INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (57, '2024-05-31', 44);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (58, '2024-05-31', 16);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (59, '2024-05-31', 80);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (60, '2024-05-31', 48);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (61, '2024-05-31', 289);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (62, '2024-05-31', 21);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (63, '2024-05-31', 35);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (64, '2024-05-31', 86);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (65, '2024-05-31', 91);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (66, '2024-05-31', 140);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (67, '2024-05-31', 309);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (68, '2024-05-31', 244);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (69, '2024-05-31', 21);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (70, '2024-05-31', 0);

INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (71, '2024-05-31', 14);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (72, '2024-05-31', 122);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (73, '2024-05-31', 22);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (74, '2024-05-31', 26);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (75, '2024-05-31', 55);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (76, '2024-05-31', 29);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (77, '2024-05-31', 34);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (78, '2024-05-31', 23);
