INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (1, '2024-06-30', 23);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (2, '2024-06-30', 80);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (3, '2024-06-30', 102);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (4, '2024-06-30', 26);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (5, '2024-06-30', 36);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (6, '2024-06-30', 67);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (7, '2024-06-30', 65);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (8, '2024-06-30', 20);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (9, '2024-06-30', 34);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (10, '2024-06-30', 66);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (11, '2024-06-30', 94);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (12, '2024-06-30', 258);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (13, '2024-06-30', 94);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (14, '2024-06-30', 108);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (15, '2024-06-30', 208);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (16, '2024-06-30', 131);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (17, '2024-06-30', 31);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (18, '2024-06-30', 56);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (19, '2024-06-30', 28);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (20, '2024-06-30', 344);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (21, '2024-06-30', 41);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (22, '2024-06-30', 24);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (23, '2024-06-30', 49);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (24, '2024-06-30', 34);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (25, '2024-06-30', 1580);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (26, '2024-06-30', 75);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (27, '2024-06-30', 27);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (28, '2024-06-30', 17);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (29, '2024-06-30', 105);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (30, '2024-06-30', 23);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (31, '2024-06-30', 276);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (32, '2024-06-30', 197);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (33, '2024-06-30', 36);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (34, '2024-06-30', 57);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (35, '2024-06-30', 131);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (36, '2024-06-30', 38);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (37, '2024-06-30', 28);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (38, '2024-06-30', 330);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (39, '2024-06-30', 67);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (40, '2024-06-30', 782);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (41, '2024-06-30', 79);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (42, '2024-06-30', 44);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (43, '2024-06-30', 91);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (44, '2024-06-30', 191);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (45, '2024-06-30', 17);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (46, '2024-06-30', 46);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (47, '2024-06-30', 28);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (48, '2024-06-30', 19);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (49, '2024-06-30', 83);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (50, '2024-06-30', 166);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (51, '2024-06-30', 50);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (52, '2024-06-30', 145);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (53, '2024-06-30', 203);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (54, '2024-06-30', 88);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (55, '2024-06-30', 51);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (56, '2024-06-30', 64);

INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (57, '2024-06-30', 44);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (58, '2024-06-30', 19);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (59, '2024-06-30', 76);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (60, '2024-06-30', 52);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (61, '2024-06-30', 295);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (62, '2024-06-30', 20);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (63, '2024-06-30', 34);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (64, '2024-06-30', 82);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (65, '2024-06-30', 94);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (66, '2024-06-30', 139);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (67, '2024-06-30', 300);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (68, '2024-06-30', 242);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (69, '2024-06-30', 59);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (70, '2024-06-30', 22);

INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (71, '2024-06-30', 14);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (72, '2024-06-30', 122);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (73, '2024-06-30', 22);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (74, '2024-06-30', 26);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (75, '2024-06-30', 55);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (76, '2024-06-30', 29);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (77, '2024-06-30', 34);
INSERT INTO GROUP_MONTH_STATISTIC(STATISTIC_GROUP_ID, STATISTIC_MEASURED_AT, STATISTIC_MEMBER_COUNT)
VALUES (78, '2024-06-30', 23);
